[mypy]
python_version = 3.10
ignore_missing_imports = True
follow_imports = skip
warn_unused_configs = False
warn_unreachable = False
allow_untyped_defs = True
allow_untyped_calls = True
allow_subclassing_any = True
disable_error_code = assignment,attr-defined,call-arg,arg-type,index,operator,return-value,union-attr

[mypy-mmm.*]
ignore_errors = True

